### PR TITLE
read root level composer + user configuration files

### LINKED ISSUE #380: Bug: Warning: file_get_contents of composer.json
Latest version of CF plugin, when visiting WP admin Settings->Cloudflare dashboard.. You can see a red bar below in a page, and getting an error each time:

```
wp-content/plugins/cloudflare/src/WordPress/composer.json): failed to open stream: No such file or directory
```

### PR DESCRIPTION
**Pull request by jacobbednarz**
During the CI revamp, we pulled out a manual step that would copy the
`composer.json` file into the same directory as the `PluginsActions`
class. This seems quite verbose so instead of restoring that
functionality, let's just reuse the root level files.

Closes #380

### CODE REVIEW

**Review by manatarms — APPROVED** [review]

File: src/WordPress/PluginActions.php [hunk 1]
```diff
@@ -53,6 +53,9 @@ class PluginActions extends AbstractPluginActions
         'integrationName',
     ];
 
+    const USER_CONFIG_PATH = '/../../config.json';
```
Comment (manatarms) [inline src/WordPress/PluginActions.php:56]: I remember at some point there was a script that nuked the root level config and composer jsons. Can we confirm that these exist in the release zips?

Comment (jacobbednarz) [reply src/WordPress/PluginActions.php:56]: yep, we definitely do keep it around. both archives (GitHub + WordPress SVN) are showing it as present.

```
$ wget https://downloads.wordpress.org/plugin/cloudflare.4.2.1.zip
$ unzip -l cloudflare.4.2.1.zip | grep -e "composer\.json" -e "config\.json"
     1309  03-05-2021 20:13   cloudflare/composer.json
      807  03-05-2021 20:13   cloudflare/config.json
      879  12-12-2017 15:07   cloudflare/vendor/cloudflare/cf-ip-rewrite/composer.json
      594  10-02-2020 04:01   cloudflare/vendor/cloudflare/cloudflare-plugin-backend/composer.json
      561  06-29-2020 13:39   cloudflare/vendor/psr/log/composer.json
```
